name = "artists-against-taupe"
compatibility_date = "2024-12-13"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "artists-against-taupe"
database_id = "02446ffe-8812-47d9-8c90-f8c93cd0ce43"

# Environment variables (secrets should be set with wrangler secret put)
[vars]
# Non-sensitive variables can go here

# Build configuration for Pages Functions
[build]
command = "npm run build"