name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - 'feature/**'  # Deploy all feature branches
      - 'fix/**'      # Deploy all fix branches
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_TURNSTILE_SITE_KEY }}
          VITE_R2_PUBLIC_URL: https://images.artistsagainsttaupe.com

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy dist --project-name=artists-against-taupe
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}